SystemOrganization addCategory: #Squelch!
SystemOrganization addCategory: 'Squelch-Blocks'!
SystemOrganization addCategory: 'Squelch-Execution Engine'!
SystemOrganization addCategory: 'Squelch-Networking'!
SystemOrganization addCategory: 'Squelch-Object IO'!
SystemOrganization addCategory: 'Squelch-Objects'!
SystemOrganization addCategory: 'Squelch-Paint'!
SystemOrganization addCategory: 'Squelch-Plugins'!
SystemOrganization addCategory: 'Squelch-Sound'!
SystemOrganization addCategory: 'Squelch-Translation'!
SystemOrganization addCategory: 'Squelch-UI-Dialogs'!
SystemOrganization addCategory: 'Squelch-UI-Panes'!
SystemOrganization addCategory: 'Squelch-UI-Support'!
SystemOrganization addCategory: 'Squelch-UI-Watchers'!
